version: '3'
services:
  db:
    image: postgres:12
    network_mode: "bridge"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuserpass
      POSTGRES_DB: testdb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - /tmp:/tmp
    restart: always
  redis:
    image: redis
    network_mode: "bridge"
    volumes:
      - ./redis_data:/data
    restart: always
  hive:
    depends_on:
      - db
      - redis
    build: .
    network_mode: "bridge"
    environment:
      LOG_LEVEL: DEBUG
      DATABASE_URL: postgresql://testuser:testuserpass@db:5432/testdb
      STEEMD_URL: https://api.moecki.online
      REDIS_URL: redis://redis:6379
      MAX_BATCH: 50
      MAX_WORKERS: 4
      SYNC_SERVICE: 0
    links:
      - db:db
      - redis:redis
    ports:
      - 8081:8080
    restart: always
