version: '3'
services:
  db:
    image: postgres:12
    network_mode: "bridge"
    environment:
      POSTGRES_USER: steem
      POSTGRES_PASSWORD: steem123
      POSTGRES_DB: hivedb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
      - /tmp:/tmp
    restart: always
  redis:
    image: redis
    network_mode: "bridge"
    volumes:
      - ./redis_data:/data
    restart: always
  hive:
    depends_on:
      - db
      - redis
    image: steemit/hivemind:latest
    network_mode: "bridge"
    environment:
      DATABASE_URL: postgresql://steem:steem123@db:5432/hivedb
      LOG_LEVEL: DEBUG
      TEST_DISABLE_SYNC: 1
      STEEMD_URL: http://api.moecki.online # This is the fullnode api
      REDIS_URL: redis://redis:6379
      SYNC_SERVICE: 1
      MAX_BATCH: 50
      MAX_WORKERS: 2
    ports:
      - "8081:8080"
    links:
      - db:db
      - redis:redis
    restart: always
