version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuserpass
      POSTGRES_DB: testdb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis
    volumes:
      - ./redis_data:/data
    restart: always
  hive:
    depends_on:
      - db
      - redis
    image: steemit/hivemind:latest
    environment:
      LOG_LEVEL: INFO
      DATABASE_URL: postgresql://testuser:testuserpass@db:5432/testdb
      STEEMD_URL: https://api.steemit.com
      REDIS_URL: redis://redis:6379
    links:
      - db:db
      - redis:redis
    ports:
      - 8080:8080
    restart: always
