version: '3'
services:
  db:
    image: postgres:12
    network_mode: "bridge"
    environment:
      POSTGRES_USER: steem
      POSTGRES_PASSWORD: steem123
      POSTGRES_DB: hivedb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis
    network_mode: "bridge"
    volumes:
      - ./redis_data:/data
    restart: always
  hive:
    depends_on:
      - db
      - redis
    build: .
    network_mode: "bridge"
    environment:
      LOG_LEVEL: DEBUG
      DATABASE_URL: postgresql://steem:steem123@db:5432/hivedb
      STEEMD_URL: https://api.moecki.online
      REDIS_URL: redis://redis:6379
    links:
      - db:db
      - redis:redis
    ports:
      - 8081:8080
    restart: always
